# Generated by Django 5.1.3 on 2024-11-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boatTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('regno', models.BigIntegerField()),
                ('fitness', models.FileField(upload_to='')),
                ('no_of_passengers', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=100)),
                ('certificate', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='driverTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phno', models.BigIntegerField()),
                ('license', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='loginTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='routeTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromRoute', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='camera_notificationTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('BOAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boattbl')),
            ],
        ),
        migrations.CreateModel(
            name='emergencyTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('details', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drivertbl')),
            ],
        ),
        migrations.CreateModel(
            name='insuranceTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('validity', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('BOAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boattbl')),
            ],
        ),
        migrations.CreateModel(
            name='locationTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drivertbl')),
            ],
        ),
        migrations.AddField(
            model_name='drivertbl',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintbl'),
        ),
        migrations.CreateModel(
            name='ownerTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phno', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='notificationTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('date', models.DateField()),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drivertbl')),
                ('OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ownertbl')),
            ],
        ),
        migrations.AddField(
            model_name='drivertbl',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ownertbl'),
        ),
        migrations.AddField(
            model_name='boattbl',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ownertbl'),
        ),
        migrations.CreateModel(
            name='stopTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ROUTE', models.ForeignKey(on_delete=models.Model, to='myapp.routetbl')),
            ],
        ),
        migrations.CreateModel(
            name='timescheudle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripname', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('BOAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boattbl')),
                ('ROUTE', models.ForeignKey(on_delete=models.Model, to='myapp.routetbl')),
            ],
        ),
        migrations.CreateModel(
            name='timescheudle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('STOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stoptbl')),
                ('timeschedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.timescheudle')),
            ],
        ),
        migrations.CreateModel(
            name='userTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phno', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='feedbackTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('BOAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boattbl')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl')),
            ],
        ),
        migrations.CreateModel(
            name='complaintTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('BOAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boattbl')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl')),
            ],
        ),
        migrations.CreateModel(
            name='bookingTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromRoute', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('no_of_passengers', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('BOAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boattbl')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl')),
            ],
        ),
    ]
