# Generated by Django 5.1.3 on 2025-01-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('BOAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boattbl')),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drivertbl')),
            ],
        ),
    ]
