# Generated by Django 5.1.3 on 2025-01-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assign_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertbl',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
