# Generated by Django 5.1.3 on 2025-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usertbl_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='boattbl',
            name='qr',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
