# Generated by Django 5.1.3 on 2025-02-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_boattbl_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boattbl',
            old_name='qr',
            new_name='qryt',
        ),
    ]
