from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.login, name='login'),
    path('adminhome', views.adminhome, name='adminhome'),
    path('adminForgotPassword', views.adminForgotPassword, name='adminForgotPassword'),
    path('manage_seats',views.manage_seats, name = 'manage_seats'),
    path('registration',views.registration, name = 'registration'),
    path('registration_post',views.registration_post, name = 'registration_post'),
    path('reply/<id>',views.reply, name='reply'),
    path('reply_post',views.reply_post, name='reply_post'),
    path('track_boat',views.track_boat, name='track_boat'),
    path('verify_boat', views.verify_boat, name='verify_boat'),
    path('view_complaint', views.view_complaint, name='view_complaint'),
    path('view_drivers', views.view_drivers, name='view_drivers'),
    path('view_emergency', views.view_emergency, name='view_emergency'),
    path('view_owner', views.view_owner, name='view_owner'),
    path('view_timeschedule/<id>', views.view_timeschedule, name='view_timeschedule'),
    path('view_timeschedule_card/<id>', views.view_timeschedule_card, name='view_timeschedule_card'),
    path('assign_boat/<id>', views.assign_boat, name='assign_boat'),
    path('login_post', views.login_post, name='login_post'),
    path('assign_boat_post', views.assign_boat_post, name='assign_boat_post'),
    path('admin_search_owner', views.admin_search_owner, name='admin_search_owner'),
    path('accept_owner/<id>',views.accept_owner,name='accept_owner'),
    path('reject_owner/<id>',views.reject_owner,name='reject_owner'),
    path('accept_boat/<id>',views.accept_boat,name='accept_boat'),
    path('reject_boat/<id>',views.reject_boat,name='reject_boat'),
    path('verify_boat_search',views.verify_boat_search,name='verify_boat_search'),
    path('view_drivers_search',views.view_drivers_search,name='view_drivers_search'),
    path('admin_view_assign_and_track',views.admin_view_assign_and_track,name='admin_view_assign_and_track'),


    path('owner_add_and_manage_driver',views.owner_add_and_manage_driver,name='owner_add_and_manage_driver'),
    path('owner_add_new',views.owner_add_new,name='owner_add_new'),
    path('owner_add_new_post',views.owner_add_new_post,name='owner_add_new_post'),
    path('owner_addnew_add_and_managedriver',views.owner_addnew_add_and_managedriver,name='owner_addnew_add_and_managedriver'),
    path('owner_addnew_add_and_managedriver_post',views.owner_addnew_add_and_managedriver_post,name='owner_addnew_add_and_managedriver_post'),
    # path('owner_addnew_add_and_managedriver',views.owner_addnew_add_and_managedriver,name='owner_addnew_add_and_managedriver'),
    path('owner_Addnew_insurance',views.owner_Addnew_insurance,name='owner_Addnew_insurance'),
    path('owner_Addnew_insurance_post',views.owner_Addnew_insurance_post,name='owner_Addnew_insurance_post'),
    path('owner_add_or_manage_insurance',views.owner_add_or_manage_insurance,name='owner_add_or_manage_insurance'),
    path('owner_add_or_manage_insurance',views.owner_add_or_manage_insurance,name='owner_add_or_manage_insurance'),
    path('owner_assign_add_and_manage',views.owner_assign_add_and_manage,name='owner_assign_add_and_manage'),
    path('owner_edit_add_and_manage_driver/<id>',views.owner_edit_add_and_manage_driver,name='owner_edit_add_and_manage_driver'),
    path('owner_delete_driver/<id>',views.owner_delete_driver,name='owner_delete_driver'),
    path('owner_sendreply/<id>',views.owner_sendreply,name='owner_sendreply'),
    path('owner_edit_add_or_manage_insurance',views.owner_edit_add_or_manage_insurance,name='owner_edit_add_or_manage_insurance'),
    path('owner_edit_boat_details',views.owner_edit_boat_details,name='owner_edit_boat_details'),
    path('owner_edit_add_and_manage_driver_post',views.owner_edit_add_and_manage_driver_post,name='owner_edit_add_and_manage_driver_post'),
    path('owner_home',views.owner_home,name='owner_home'),
    path('owner_send_notification_driver/<id>',views.owner_send_notification_driver,name='owner_send_notification_driver'),
    path('owner_track_driver',views.owner_track_driver,name='owner_track_driver'),
    path('owner_send_notification_driver_post',views.owner_send_notification_driver_post,name='owner_send_notification_driver_post'),
    path('owner_view_complaints_and_send_reply',views.owner_view_complaints_and_send_reply,name='owner_view_complaints_and_send_reply'),
    path('owner_sendreply_post',views.owner_sendreply_post,name='owner_sendreply_post'),
    path('owner_view_more',views.owner_view_more,name='owner_view_more'),
    path('owner_view_boat',views.owner_view_boat,name='owner_view_boat'),
    path('owner_edit_new_post',views.owner_edit_new_post,name='owner_edit_new_post'),
    path('delete_owner_view_boat/<int:id>',views.delete_owner_view_boat,name='delete_owner_view_boat'),
    path('owner_edit_new/<int:id>',views.owner_edit_new,name='owner_edit_new'),
    path('owner_view_emergency_notification',views.owner_view_emergency_notification,name='owner_view_emergency_notification'),
    path('owner_view_feedback',views.owner_view_feedback,name='owner_view_feedback'),
    path('owner_view_tripdetails/<int:id>',views.owner_view_tripdetails,name='owner_view_tripdetails'),

    path('owner_add_tripdetails/<id>',views.owner_add_tripdetails,name='owner_add_tripdetails'),
    path('owner_add_tripdetails_post',views.owner_add_tripdetails_post,name='owner_add_tripdetails_post'),
    path('owner_delete_triptime/<id>',views.owner_delete_triptime,name='owner_delete_triptime'),


    path('logincode',views.logincode,name='logincode'),
    path('driver_view_profile',views.driver_view_profile,name='driver_view_profile'),
    path('view_notification',views.view_notification,name='view_notification'),
    path('sendemergency',views.sendemergency,name='sendemergency'),
    path('registrationcode',views.registrationcode,name='registrationcode'),
    path('show_boat',views.show_boat,name='show_boat'),
    path('sendrating2',views.sendrating2,name='sendrating2'),
    path('sendcomplaint',views.sendcomplaint,name='sendcomplaint'),
    path('viewreply',views.viewreply,name='viewreply'),
    path('delete_complaint',views.delete_complaint,name='delete_complaint'),
    path('and_view_profile',views.and_view_profile,name='and_view_profile'),
    path('manage_route_post',views.manage_route_post,name='manage_route_post'),
    path('view_rooute',views.view_rooute,name='view_rooute'),
    path('manage_stop/<id>',views.manage_stop,name='manage_stop'),
    path('dlete_stop/<id>',views.dlete_stop,name='dlete_stop'),
    path('dlete_route/<id>',views.dlete_route,name='dlete_route'),
    path('owner_edit_insurence/<id>',views.owner_edit_insurence,name='owner_edit_insurence'),
    path('owner_delete_insurencedetails/<id>',views.owner_delete_insurencedetails,name='owner_delete_insurencedetails'),
    path('add_stop',views.add_stop,name='add_stop'),
    path('add_stop_post',views.add_stop_post,name='add_stop_post'),
    path('owner_search_driver',views.owner_search_driver,name='owner_search_driver'),
    path('owner_search_insuranceboat',views.owner_search_insuranceboat,name='owner_search_insuranceboat'),
    path('logout',views.logout,name='logout'),
    path('owner_edit_insurance_post',views.owner_edit_insurance_post,name='owner_edit_insurance_post'),
    path('/view_myassignedboat',views.view_myassignedboat,name='view_myassignedboat'),
    path('qrscanandview',views.qrscanandview,name='qrscanandview'),
    path('updatelocation',views.updatelocation,name='updatelocation'),
    path('count/<int:co>/<int:id>', views.count, name="count"),



]
